from __future__ import annotations

from typing import Any, Protocol


class AuthService(Protocol):
    async def verify(self, identifier: str, **kwargs: Any) -> dict[str, Any]:
        """Verify customer identity. Returns customer data if verified."""
        ...


class AccountService(Protocol):
    async def get_balance(self, account_id: str) -> dict[str, Any]: ...
    async def get_transactions(self, account_or_card_id: str, **kwargs: Any) -> dict[str, Any]: ...


class CardService(Protocol):
    async def block_card(self, card_id: str, reason: str) -> dict[str, Any]: ...
    async def order_replacement(self, card_id: str, shipping: str) -> dict[str, Any]: ...
    async def get_details(self, card_id: str) -> dict[str, Any]: ...
    async def block_merchant(self, card_id: str, merchant_id: str) -> dict[str, Any]: ...
    async def file_dispute(self, **kwargs: Any) -> dict[str, Any]: ...


class LoanService(Protocol):
    async def check_eligibility(self, customer_id: str, amount: float, purpose: str) -> dict[str, Any]: ...
    async def calculate_emi(self, amount: float, rate: float, terms: list[int]) -> dict[str, Any]: ...
    async def check_mortgage_eligibility(self, **kwargs: Any) -> dict[str, Any]: ...


class TransferService(Protocol):
    async def get_exchange_rate(self, from_currency: str, to_currency: str, amount: float) -> dict[str, Any]: ...
    async def initiate_transfer(self, **kwargs: Any) -> dict[str, Any]: ...


class DocumentService(Protocol):
    async def generate_statement(self, account_id: str, months: int, **kwargs: Any) -> dict[str, Any]: ...
    async def get_tax_document(self, customer_id: str, tax_year: int, doc_type: str) -> dict[str, Any]: ...
    async def email_document(self, document_ids: list[str], email: str | None = None) -> dict[str, Any]: ...


class ComplaintService(Protocol):
    async def get_history(self, customer_id: str) -> dict[str, Any]: ...
    async def get_case_status(self, case_id: str) -> dict[str, Any]: ...
    async def file_complaint(self, **kwargs: Any) -> dict[str, Any]: ...
    async def initiate_human_transfer(self, **kwargs: Any) -> dict[str, Any]: ...
